CREATE USER IF NOT EXISTS `writer`@'%' IDENTIFIED BY 'QWER1qaz@#$';
GRANT ALL PRIVILEGES ON *.* to 'writer'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS `reader`@'%' IDENTIFIED BY 'QWER1qaz@#$';
GRANT SELECT on *.* to 'reader'@'%' WITH GRANT OPTION;